# Configuration file for testing a trained SRRESNET model.

experiment_name: "SRRESNET/test_1"
model_type: "SRRESNET"
weights_path: "models/SRRESNET/generator_epoch_204.torch"  # Specify a path to load from a pretrained model
task: "test" # in ('train', 'test', 'predict')

paths:
  test_set:
    [
      "data/raw/test/BSD100",
      "data/raw/test/Set5",
      "data/raw/test/Set14",
    ]
  test_images_save:
    [
      "data/processed/test/BSD100",
      "data/processed/test/Set5",
      "data/processed/test/Set14",
    ]
